use 19pw22;

#show tables;

#Qn1
CREATE TABLE IF NOT EXISTS EMPTABLE
(
    EmpId NUMERIC(6) PRIMARY KEY,
    Name VARCHAR(10) NOT NULL ,
    City VARCHAR(10),
    DoB DATE NOT NULL,
    Sex VARCHAR(1),
    DoJ DATE NOT NULL,
    Salary NUMERIC(8,2),
    Department VARCHAR(10),
    CONSTRAINT Name_Check CHECK ( ASCII(LEFT(Name,1)) BETWEEN ASCII('A') AND ASCII('Z')),
    CONSTRAINT City_Check CHECK ( ASCII(LEFT(City,1)) BETWEEN ASCII('A') AND ASCII('Z')),
    CONSTRAINT Sex_Check CHECK (Sex IN('M' , 'F') ),
    CONSTRAINT Salary_Check CHECK ( Salary BETWEEN 15000 AND 50000),
    CONSTRAINT Department_Check CHECK ( Department IN ('ACC','FIN','EDP') )
);

#Qn2
INSERT INTO EMPTABLE
VALUES (1001, 'Anish', 'Chennai', STR_TO_DATE('21-apr-1966', '%d-%b-%Y'), 'M', STR_TO_DATE('10-jun-1986', '%d-%b-%Y'),
        17000, 'ACC'),
       (1002, 'Anandi', 'Ooty', STR_TO_DATE('11-sep-1975', '%d-%b-%Y'), 'F', STR_TO_DATE('17-jun-1997', '%d-%b-%Y'),
        15000,
        'FIN'),
       (1003, 'Shiva', 'Kambam', STR_TO_DATE('07-feb-1966', '%d-%b-%Y'), 'M', STR_TO_DATE('21-apr-1991', '%d-%b-%Y'),
        21000, 'EDP'),
       (1004, 'Deepa', 'Trichi', STR_TO_DATE('14-feb-1967', '%d-%b-%Y'), 'M', STR_TO_DATE('21-apr-1990', '%d-%b-%Y'),
        12000, 'FIN'),
       (1005, 'Engela', NULL, STR_TO_DATE('23-mar-1970', '%d-%b-%Y'), 'F', STR_TO_DATE('21-apr-1986', '%d-%b-%Y'),
        32000, 'EDP'),
       (1006, 'Krish', 'Trichi', STR_TO_DATE('14-jul-1970', '%d-%b-%Y'), 'F', STR_TO_DATE('21-mar-1989', '%d-%b-%Y'),
        15000, 'ACC'),
       (1007, 'Kamal', 'Ooty', STR_TO_DATE('14-jul-1966', '%d-%b-%Y'), 'M', STR_TO_DATE('04-mar-1990', '%d-%b-%Y'),
        12000,
        'FIN'),
       (1008, 'Neela', 'Madurai', STR_TO_DATE('27-jun-1969', '%d-%b-%Y'), 'F', STR_TO_DATE('07-apr-1990', '%d-%b-%Y'),
        25000, 'EDP'),
       (1009, 'Bala', 'Coimbatore', STR_TO_DATE('29-oct-1962', '%d-%b-%Y'), 'M', STR_TO_DATE('21-apr-1993', '%d-%b-%Y'),
        20000, 'ACC'),
       (1010, 'Rajesh', 'Pollachi', STR_TO_DATE('21-apr-1966', '%d-%b-%Y'), 'M', STR_TO_DATE('12-oct-1993', '%d-%b-%Y'),
        17000, 'FIN'),
       (1011, 'Rekha', 'Coimbatore', STR_TO_DATE('21-apr-1970', '%d-%b-%Y'), 'F',
        STR_TO_DATE('14-dec-1999', '%d-%b-%Y'),
        20000, 'ACC'),
       (1012, 'Xavier', 'Madurai', STR_TO_DATE('21-apr-1971', '%d-%b-%Y'), 'M', STR_TO_DATE('12-mar-1997', '%d-%b-%Y'),
        20000, 'ACC'),
       (1013, 'Vinotha', 'Trichi', STR_TO_DATE('21-apr-1972', '%d-%b-%Y'), 'F', STR_TO_DATE('21-apr-1994', '%d-%b-%Y'),
        17000, 'ACC');

# SELECT * FROM EMPTABLE;

#Qn3_01
SELECT *
FROM EMPTABLE;

#Qn3_02
SELECT EmpId , Name , City , Salary
FROM EMPTABLE;

#Qn3_03
SELECT EmpId
FROM EMPTABLE
WHERE Name = 'Bala';

#Qn3_04
SELECT *
FROM EMPTABLE
WHERE Sex = 'M';

#Qn3_05
SELECT *
FROM EMPTABLE
WHERE City='Coimbatore';

#Qn3_06
SELECT *
FROM EMPTABLE
WHERE City IN ('Coimbatore','Trichy','Chennai');

#Qn3_07
SELECT *
FROM EMPTABLE
WHERE City IS NULL;

#Qn3_08
SELECT DISTINCT City
FROM EMPTABLE;

#Qn3_09
SELECT EmpId , Salary*2
FROM EMPTABLE;

#Qn3_10
SELECT Name , City
FROM EMPTABLE
WHERE  Salary>50000;

#Qn3_11
SELECT EmpId , Name , Salary*1.05 AS 'Increased Salary'
FROM EMPTABLE;

#Qn3_12
SELECT EmpId , Name , Salary*1.05 AS 'Increased Salary'
FROM EMPTABLE
ORDER BY Salary DESC;

#Qn3_13
SELECT Name , Salary
FROM EMPTABLE
ORDER BY Salary,Name DESC ;

#Qn3_14
SELECT COUNT(EmpId)
FROM EMPTABLE;

#Qn3_15
SELECT COUNT(Department)
FROM EMPTABLE;

#Qn3_16
SELECT COUNT(*)
FROM EMPTABLE
WHERE Department='FIN';

#Qn3_17
SELECT COUNT(*)
FROM EMPTABLE
WHERE Sex='M';

#Qn3_18
SELECT Name
FROM EMPTABLE
WHERE Salary = (SELECT MAX(Salary) FROM EMPTABLE);

#Qn3_19
SELECT Name
FROM EMPTABLE
WHERE Salary = (SELECT MIN(Salary) FROM EMPTABLE);

#Qn3_20
SELECT Department,SUM(Salary)
FROM EMPTABLE
GROUP BY Department;

#Qn3_21
SELECT EmpId
FROM EMPTABLE
WHERE EmpId != 1002;

#Qn3_22
SELECT *
FROM EMPTABLE
WHERE ASCII(LEFT(Name,1)) = ASCII('A');

#Qn3_23
SELECT *
FROM EMPTABLE
WHERE DoB <DATE(STR_TO_DATE('01-JAN-91' , '%d-%b-%y'));

#Qn3_24
SELECT Name
FROM EMPTABLE
WHERE Salary BETWEEN 20000 AND 40000;

#Qn3_25
SELECT *
FROM EMPTABLE
WHERE Salary >20000;

#Qn3_26
SELECT *
FROM EMPTABLE
WHERE Department ='ACC' AND Salary >40000;

#Qn3_27
SELECT *
FROM EMPTABLE
WHERE Salary > 20000;

#Qn3_28
SELECT Name, Salary , Department
FROM EMPTABLE
WHERE (Department,Salary) IN (SELECT Department, MIN(Salary)
    FROM EMPTABLE
    GROUP BY Department);

#Qn3_29
SELECT Department,COUNT(*)
FROM EMPTABLE
WHERE Sex = 'M'
GROUP BY Department;

#Qn3_30
SELECT Name , TIMESTAMPDIFF(DAY ,DOJ,CURRENT_TIMESTAMP) AS EXPERIENCE_IN_DAYS
FROM EMPTABLE;

#Qn3_31
SELECT Name, TIMESTAMPDIFF(YEAR ,DOJ,CURRENT_TIMESTAMP) AS EXPERIENCE_IN_YEARS
FROM EMPTABLE;

#Qn3_32
SELECT Name , TIMESTAMPDIFF(YEAR ,DoB ,CURRENT_TIMESTAMP) AS AGE
FROM EMPTABLE;

#Qn3_33
SELECT *
FROM EMPTABLE
WHERE DoB = (SELECT MIN(DoB) FROM EMPTABLE);

#Qn3_34
SELECT TIMESTAMPDIFF(YEAR ,DoB ,CURRENT_TIMESTAMP) AS AGE
FROM EMPTABLE
WHERE DoB = (SELECT MIN(DoB) FROM EMPTABLE);

#Qn3_35
SELECT Name , City
FROM EMPTABLE
ORDER BY Name,City ;

#Qn3_36
SELECT Name, DoB
FROM EMPTABLE
WHERE MONTH(DoB) = '01';

#Qn3_37
SELECT Department,COUNT(*)
FROM EMPTABLE
GROUP BY Department;

#Qn3_38
#PHONE NUMBER DETAILS NOT INCLUDED

#Qn3_39
SELECT Sex , AVG(TIMESTAMPDIFF(YEAR,DoB,CURRENT_TIMESTAMP)) AS AVERAGE_AGE
FROM EMPTABLE
GROUP BY Sex;

#Qn3_40
SELECT *
FROM EMPTABLE
WHERE MONTH(DoB) = MONTH(CURRENT_TIMESTAMP);

#Qn3_41
SELECT AVG(Salary) AS AVERAGE_SALARY
FROM EMPTABLE;

#Qn3_42
SELECT Department,AVG(Salary)
FROM EMPTABLE
GROUP BY Department;

#Qn3_43
SELECT Department,SUM(Salary)
FROM EMPTABLE
GROUP BY Department;

#Qn3_44
SELECT COUNT(*)
FROM EMPTABLE
WHERE Salary >30000;

#Qn3_45
SELECT MAX(Salary)
FROM EMPTABLE;

#Qn3_46
SELECT Department,MAX(Salary)
FROM EMPTABLE
GROUP BY Department;

#Qn3_47
SELECT COUNT(*)
FROM EMPTABLE
WHERE Sex ='F' AND City = 'COIMBATORE';

#Qn3_48
SELECT *
FROM EMPTABLE
WHERE MONTH(DoB) != '10' AND MONTH(DoB) !='03';

#Qn3_49
SELECT Department,COUNT(*) AS FEMALE_EMPLOYEES
FROM EMPTABLE
WHERE Sex = 'F'
GROUP BY Department;

#Qn3_50
SELECT Name,City,DoB
FROM EMPTABLE
ORDER BY Name ;

#Qn3_51
SELECT (MAX(Salary) -MIN(Salary))
FROM EMPTABLE;

#Qn3_52
SELECT Department
FROM EMPTABLE
GROUP BY Department
ORDER BY COUNT(Department) DESC
LIMIT 1;

#Qn3_53
SELECT Department
FROM EMPTABLE
GROUP BY Department
ORDER BY COUNT(*)
LIMIT 1;

#Qn3_54
SELECT Name
FROM EMPTABLE
WHERE DoB = (SELECT DoB FROM EMPTABLE WHERE YEAR(DoB) = 1990 AND Sex ='M' ORDER BY DOB
    LIMIT 1);

#Qn3_55
SELECT Name
FROM EMPTABLE
WHERE Sex = 'F' AND YEAR(DoB) = 1990
ORDER BY DoB DESC
LIMIT 1;

#Qn3_56
SELECT Name
FROM EMPTABLE
WHERE TIMESTAMPDIFF(YEAR ,DoB,CURRENT_TIMESTAMP) < 32;

#Qn3_57
SELECT *
FROM EMPTABLE
WHERE TIMESTAMPDIFF(YEAR ,DoB,CURRENT_TIMESTAMP) < TIMESTAMPDIFF(YEAR ,(SELECT DoB
    FROM EMPTABLE
    WHERE EmpId = '1007') , CURRENT_TIMESTAMP);

#Qn3_58
SELECT YEAR(DoB)
FROM EMPTABLE
GROUP BY YEAR(DoB)
ORDER BY COUNT(DoB) DESC
LIMIT 1;

#Qn3_59
SELECT MONTH(DoB)
FROM EMPTABLE
GROUP BY MONTH(DoB)
ORDER BY COUNT(DoB) DESC
LIMIT 1;

#Qn3_60
SELECT Name
FROM EMPTABLE
WHERE Salary < (SELECT AVG(Salary) FROM EMPTABLE WHERE Sex='F') AND Sex= 'M';

#Qn3_61
SELECT *
FROM EMPTABLE
WHERE Salary IN (SELECT  Salary FROM EMPTABLE GROUP BY Salary HAVING COUNT(Salary) > 1);

#Qn3_62
SELECT COUNT(DISTINCT Department)
FROM EMPTABLE;

#Qn3_63
SELECT Name
FROM EMPTABLE
WHERE LENGTH(Name) < 5;

#Qn3_64
SELECT Name
FROM EMPTABLE
WHERE Name LIKE '%e%';

#Qn3_65
SELECT *
FROM EMPTABLE
WHERE City = 'Trichy'
  AND Department IN
    (SELECT Department FROM EMPTABLE WHERE City = 'Trichy' GROUP BY Department
    HAVING COUNT(Department) = 1);

#Qn3_66
SELECT *
FROM EMPTABLE
ORDER BY City;

#Qn3_67
SELECT City , COUNT(City)
FROM EMPTABLE
WHERE City IS NOT NULL
GROUP BY City;

#Qn3_68
SELECT Name,City,Salary
FROM EMPTABLE
WHERE (City,Salary) IN
    (SELECT City,Salary FROM EMPTABLE GROUP BY City,Salary HAVING COUNT(City) >1
    AND COUNT(City) >1);

#Qn3_69
SELECT DISTINCT Department
FROM EMPTABLE
WHERE Department NOT IN (SELECT Department FROM EMPTABLE
    WHERE City = 'Trichi');

#Qn3_70
#TO BE SOLVED

#Qn3_71
SELECT Name,Salary
FROM EMPTABLE
WHERE (Sex,Salary) IN (SELECT Sex ,Salary FROM EMPTABLE
    WHERE Sex = 'F'
    GROUP BY Salary HAVING COUNT(Salary) >1);

#Qn3_72
ALTER TABLE EMPTABLE
MODIFY COLUMN Name VARCHAR(15) NOT NULL;

#Qn3_73
ALTER TABLE EMPTABLE
ADD COLUMN Age NUMERIC(3);

#Qn3_74
UPDATE EMPTABLE
SET Age = TIMESTAMPDIFF(YEAR ,DoB,CURRENT_TIMESTAMP);

#Qn3_75
ALTER TABLE EMPTABLE
CHANGE DoB DateOfBirth DATE NOT NULL ;

#Qn3_76
ALTER TABLE EMPTABLE
DROP COLUMN Age;

#Qn3_77
#YET TO SOLVE

#Qn3_78
#SELECT fname FROM employee WHERE dept = ‘ACC’ ORDER BY 1 DESC;
#TABLE DOES NOT EXIST
SELECT Name FROM EMPTABLE
WHERE Department = 'ACC' ORDER BY 1 DESC;
#IF QUES MEANT THIS IT PRINTS THE NAME OF PEOPLE IN DEPT ACC IN DESC ORDER

#Qn3_79
ALTER TABLE EMPTABLE
MODIFY COLUMN DoJ DATE;

#Qn3_80
SELECT UPPER(Name),UPPER(City)
FROM EMPTABLE;

#Qn3_81
SELECT MONTH(DateOfBirth)
FROM EMPTABLE
GROUP BY MONTH(DateOfBirth)
ORDER BY COUNT(DateOfBirth) DESC
LIMIT 1;

#Qn3_82
#ANSWER IN Qn3_60

#Qn3_83
SELECT Name
FROM EMPTABLE
WHERE Sex = 'F'
  AND Salary > (SELECT MAX(Salary) FROM EMPTABLE WHERE Sex = 'M');

#Qn3_84
INSERT INTO EMPTABLE VALUE(1001, 'Anish', 'Chennai', STR_TO_DATE('21-apr-1966', '%d-%b-%Y'), 'M',
                            STR_TO_DATE('10-jun-1986', '%d-%b-%Y'), 17000, 'ACC');

#Qn3_85
DELETE
FROM EMPTABLE
WHERE Name = 'EnGela';